"""change most Document fields to nullable

Revision ID: 1e701e105f4f
Revises: c2e329721277
Create Date: 2025-11-06 13:45:10.137747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e701e105f4f'
down_revision: Union[str, Sequence[str], None] = 'c2e329721277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('document', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('document', 'sentiment',
               existing_type=postgresql.ENUM('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='sentiment'),
               nullable=True)
    op.alter_column('document', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('document', 'read_time_est_min',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('document', 'word_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('document', 'language_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('document', 'embedding',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'embedding',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.alter_column('document', 'language_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('document', 'word_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('document', 'read_time_est_min',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('document', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('document', 'sentiment',
               existing_type=postgresql.ENUM('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='sentiment'),
               nullable=False)
    op.alter_column('document', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('document', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
